### ISSUE TITLE
Create Hunter role for participants.

### ISSUE THREAD

**Issue by Weaselcore** [chrisphamdev/halloween-bot#3]
- [X] Add message to Info channel for players to click an emote to add a role.
- [x] Add command to strip all users of the "Hunter" role.
- [x] Add command to end event and to add medals to top hunters.
- [x] Bot to remove role if a user revokes their reaction from the message.

**Comment by chrisphamdev** [comment]
- [ ] Bot to remove role if an user revoke their reaction from the message.

**Comment by Weaselcore** [comment]
- Added role_id to config file so the role_id isn't hard coded.
- Added intents parameter to allow the bot to see members.
